### ISSUE TITLE
Support shell command in OSX [was: Feature Request: Add new application to Django project ]

### ISSUE THREAD

**Issue by mkoistinen** [titoBouzout/SideBarEnhancements#111]
Would be awesome if I could right-click on my projects 'apps' folder and invoke some menu item to create the scaffolding for a new application, either via `python manage.py startapp …` or just a folder designated somewhere that contains pre-built scaffolding.

I'd make it myself, but according to the docs, invoking shell commands on Mac OS X is not supported.

Is there another way I could do this now?

[title edited by tito]

**Comment by titoBouzout** [comment]
I think this is now fixed, I mean, you can add command line arguments.
