### ISSUE TITLE
Feature request: duplicate even if destination exists

### ISSUE THREAD

**Issue by trumbitta** [titoBouzout/SideBarEnhancements#115]
In my work routine, I often need to duplicate files that exist at destination.

Asking this because using Duplicate with its handy path bar is way quicker and safer than using copy & paste, and I really thank you for this single feature in SideBarEnhancements :love_letter: 

The new feature could be an addition to the current duplicate: "Force duplicate". 
Or a simple prompt to the user in the current Duplicate: "Destination exists. Overwrite?"

In addition to this, a "Duplicate as symlink" would be very handy aswell :)

**Comment by titoBouzout** [comment]
I noted this issue on index
