### ISSUE TITLE
Find Files Named stopped working

### ISSUE THREAD

**Issue by lovette** [titoBouzout/SideBarEnhancements#227]
Same for Find Advanced > In Paths Containing. The "Instant File Search" tab opens but it's blank and ignores keyboard input. I removed and reinstalled the package to no avail. It worked earlier this week for sure. I'm on Sublime version 3.

**Comment by titoBouzout** [comment]
I think is now fixed and improved, but can you please confirm. Thanks

**Comment by lovette** [comment]
I can now type into the field, but no results are ever shown. I removed and re-installed the package, both after ST restarts.

**Comment by titoBouzout** [comment]
OK thanks, now maybe fixed for OSX

**Comment by lovette** [comment]
Looks good. 

Is there an easy way to open file(s) listed in the results?

**Comment by titoBouzout** [comment]
open-include package
