### ISSUE TITLE
Delete file leaves open tab

### ISSUE THREAD

**Issue by akrabat** [titoBouzout/SideBarEnhancements#241]
In OS X, if I right click on a file and choose the Delete option from the context menu, then a tab is opened for this file which doesn't disappear. Instead it is marked as unsaved so that when I close it it then asks me if I want to save it…

Without SideBarEnhancements, deleting a file using the sidebar context menu will close the tab automatically.

**Comment by titoBouzout** [comment]
Delete file leaves open tab when the view is transient? But it gets closed when is open right?

**Comment by akrabat** [comment]
Nope. Same thing happens when I have the file open in tab and then right click it.

**Comment by titoBouzout** [comment]
okei this was working previously... let me check..

**Comment by titoBouzout** [comment]
do you have "close_affected_buffers_when_deleting_even_if_dirty" set to true?

**Comment by akrabat** [comment]
~/Library/Application Support/Sublime Text 3/Packages/SidebarEnhancements/Side bar.sublime-settings has it set to false. I can't see it set anywhere else.

**Comment by titoBouzout** [comment]
okei.. set it to true!

**Comment by akrabat** [comment]
That works!

Can't help but wonder why the default is false :)

**Comment by titoBouzout** [comment]
the default is false alarm because if you don't notice the behaviour, you
may lose a file

**Comment by titoBouzout** [comment]
remove that 'alarm' word from previous sentence
