### ISSUE TITLE
Edit file permissions

### ISSUE THREAD

**Issue by dtjones** [titoBouzout/SideBarEnhancements#242]
This is more of a feature request than an issue, sorry. As I am using windows and i am currently using my ftp client to change file permissions. 
I would like the ability to right click on a file/folder a click 'permissions' which would either allow me to write 0777 in a textbox or to check the necessary read/write/execute checkboxes to change its permissions. 
I thought this might be useful to others as well, hope you consider it. 

Many thanks

**Comment by titoBouzout** [comment]
Changing file permission on a FTP folder is a job for a FTP package.. do you still want to have the ability to do it on local files?

**Comment by dtjones** [comment]
I don't know where file permissions are stored. If the permissions aren't transferred with the files and need to be set again on the server then this feature wouldn't be much use, but if I could change the permissions in sublime and push these changes to my repo for deployment (http://dploy.io/)  then that would be quite useful.

**Comment by titoBouzout** [comment]
the FTP packages allows you to edit permissions
