### ISSUE TITLE
Keyboard shortcuts when navigating sidebar?

### ISSUE THREAD

**Issue by aaronbushnell** [titoBouzout/SideBarEnhancements#244]
Thanks for your work on this awesome plugin.

One thing I love about NERDtree for Vim is being able to use keyboard shortcuts to rename/delete/move/etc files when the sidebar is in focus. Is there a way to do that currently with SideBarEnhancements? For example, use `CMD+Delete` to delete a file, `CMD+m` to move, `CMD+r` to rename.

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/SideBarEnhancements/issues/223
