### ISSUE TITLE
Can't find SideBarEnhancements in Sublime Text 2 Package Control

### ISSUE THREAD

**Issue by rahilsondhi** [titoBouzout/SideBarEnhancements#246]
I'm running version 2.0.2 build 2221

**Comment by JKGisMe** [comment]
Read the first line of the readme.md. 

"Sublime Text 3+"

**Comment by rahilsondhi** [comment]
Whoops

**Comment by rahilsondhi** [comment]
There are a few references to `ST2` in the README so I assumed this package was compatible with ST2.

**Comment by titoBouzout** [comment]
https://dl.dropboxusercontent.com/u/9303546/tmp/Untitled-1.jpg
