### ISSUE TITLE
refresh on file changes

### ISSUE THREAD

**Issue by justin-hackin** [titoBouzout/SideBarEnhancements#247]
I started using Ember with the CLI and found it to be a bit annoying to have to refresh the folder whenever it adds a file.  It would be really awesome if this happened automatically, watching for file changes, or even if I could add a hotkey to refresh all folders.

**Comment by titoBouzout** [comment]
If I add a hotkey to refresh folder, is very probably that that hotkey will  conflict with some other hotkey, so better, go to 

Preferences -> Key Bindings - User, then paste this somewhere:

    {"keys": ["ctrl+b"], "command": "refresh_folder_list"}

**Comment by justin-hackin** [comment]
Oh, thanks for the tip :+1:
