### ISSUE TITLE
Delete multiple directories

### ISSUE THREAD

**Issue by Pictor13** [titoBouzout/SideBarEnhancements#249]
Hi,

I just wanted to report that I'm trying to use the extension to _"Delete"_ more than one directory at once, from the sidebar.

I selected 5 directories, right click, _Delete_, and i get a
> Delete the selected items?

<sup>(note the ending plural _"s"_)</sup>

I then get asked
> Permanently Delete: \<path to the first directory in the selection\>

And if I confirm it just deletes that directory, letting all the others intact.

Would it be possible to fix this behaviour?

Except for that the extension is really really useful, thanks for it :+1:

**Comment by titoBouzout** [comment]
That happens when deleting one of any of the directories fails. As is not able to send the directory to the trash bin it ask for permanent deletion.

**Comment by Pictor13** [comment]
Mmmh ,
the filesystem directories I'm working on are coming form a _NFS_ mounted from a Linux distribution on a virtual machine.
We don't use any "Trash-bin like" strategy. When we delete a file, they are deleted for real; not moved to the trash bin.

Anyway I just made some further test.

* I create 2 directories: _dir1_ and _dir2_
* In the SideBar I select _dir1_ and _dir2_, and delete them
    * I get asked, in a pop-up, if I want to delete the directorie**s**, and I click OK
    * I get asked (above the status bar) a confirmation for the deletion of _dir1_. I press ok.
* _dir1_ is deleted, _dir2_ is not (maybe there is some problem deleting _dir2_)
* In the SideBar I delete _dir2_.
    * I get asked, in a pop-up, if I want to delete the directorie**s**, and I click OK
    * I get asked (above the status bar) a confirmation for the deletion of _dir2_. I press ok.
* _dir2_ is deleted

I also tried other combination, and that's not simply able to delete more than one directory at the same time. It always deletes **just the first one**.

On OSX instead (with Trash bin enabled) it works correctly.
The only difference is that it doesn't ask for any confirmation; probably because it is just moved to the Trash bin instead of being really deleted.

I don't know exactly how Sublime extension development works and if that second confirmation request (**not** the one in the pop-up) is automatic or if you coded to ask that, but I'm pretty sure that the issue is caused from a mistake in managing the response from the deletion, that is different from expected.

Maybe, but just maybe, could be that the kind of response is different cause of:
* missing trash-bin
or 
* different filesystem (_NFS_ instead of _HFS+_)

**Comment by titoBouzout** [comment]
It was made on purpose in that way, I agree it can be improved.. and I understand that the concept of trash bin does not exists in some situation, so good point.. let me check, thanks for so dedicated reply

**Comment by titoBouzout** [comment]
I think is fixed, didn't test

**Comment by Pictor13** [comment]
I tested.
Now a new pop-up appears:

> "There is no trash bin, permanently delete?"

And seems to work perfectly! 

Thank you for the rapid fixing! SideBarEnhancements is even more useful than before :+1:
