### ISSUE TITLE
Uanble to install via Package Control 

### ISSUE THREAD

**Issue by TechplexEngineer** [titoBouzout/SideBarEnhancements#251]
Doing a search on packagecontrol.io
https://packagecontrol.io/search/sidebar

No listings.

**Comment by titoBouzout** [comment]
It also does not appear in https://packagecontrol.io/browse/popular
may @wbond knows something about it

**Comment by wbond** [comment]
Should be fixed now. There were some networking issues with the crawler.

**Comment by titoBouzout** [comment]
okei, Thanks! =)
