### ISSUE TITLE
Focus does not follow click

### ISSUE THREAD

**Issue by appsforartists** [titoBouzout/SideBarEnhancements#252]
If I have two windows open and I right-click the background window to make a new folder, the folder naming prompt appears in the foreground window.  If I complete the prompt, the folder is made in the correct place.

Although the final result is correct, the experience is confusing.

**Comment by titoBouzout** [comment]
Please fill the issue here: https://github.com/SublimeTextIssues/Core/issues
This is not related to this package, but to the change of focus when the menu is open, also please mention which operative system, because on windows, works correctly.
