### ISSUE TITLE
New file in selected folder

### ISSUE THREAD

**Issue by ssang** [titoBouzout/SideBarEnhancements#253]
I understand that there in an option in the right-click menu to create a file in the selected folder but I was wondering if there could be keybind for it. Or, at least allow us to adjust the root for "side_bar_new_file2" to the selected folder or something. It would really increase productivity,

**Comment by titoBouzout** [comment]
Unfortunately we cannot do that because of this 
https://github.com/SublimeTextIssues/Core/issues/301
