### ISSUE TITLE
Readme: "Just DON'T install manually"

### ISSUE THREAD

**Issue by gerardroche** [titoBouzout/SideBarEnhancements#259]
At the top of the readme it says:

Sublime Text 3+ Package. Install via an updated version of Package Control 2. Just DON'T install manually.

Does this mean there is bad reason why we shouldn't install by cloning SideBarEnhancements into the ST Packages directory?

**Comment by titoBouzout** [comment]
no is just a generic message, because people later has problems to
uninstall, upgrade, etc, also they try to install in ST 2 which has been
deprecated by almost all of my packages

**Comment by gerardroche** [comment]
Cool.
