### ISSUE TITLE
[Feature Request] Prevent "preview_on_click" from triggering on right-click

### ISSUE THREAD

**Issue by RevanProdigalKnight** [titoBouzout/SideBarEnhancements#265]
Title says it all, really.

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/SideBarEnhancements/issues/187
https://github.com/SublimeTextIssues/Core/issues/2

**Comment by websash** [comment]
Well, Sublime's default Delete command also closes the tab for the deleted file without any confirmations. This isn't the case for SideBarEnhancements's command. You have to close the open tab (which shouldn't be opened in the first place, sublime's bug, I know) manually and hit **Don't save** in that confirmation window. Pretty annoying

**Comment by titoBouzout** [comment]
in SideBarEnhancements settings there is 
	"close_affected_buffers_when_deleting_even_if_dirty": false,

**Comment by websash** [comment]
Does the trick, thanks!
