### ISSUE TITLE
Create new file in same directory as current view

### ISSUE THREAD

**Issue by HurricaneJames** [titoBouzout/SideBarEnhancements#266]
The readme.md notes say that ctrl+t should create a new file in the same directory as the current file. However, at least on mac, cmd+t opens up the tab switcher. Is there a way to make cmd+n create a new file in the same directory as the current view? That is the default without SideBarEnhancements.

**Comment by titoBouzout** [comment]
This package used to provide key bindings, but no longer, add this one Menu -> Prefences -> Key Bindings - User

        {
            "keys": ["ctrl+t"],
            "command": "side_bar_new_file2"
        }

**Comment by HurricaneJames** [comment]
Thanks

**Comment by HurricaneJames** [comment]
For anybody who finds this, you will want the command to be `side_bar_new_file` to make the new file relative to the current current view, which is what the `super+n` command `new_file` does without SideBarEnhancements installed. `side_bar_new_file2` makes it relative to the project root.
