### ISSUE TITLE
Sublime text 3 crashes when I create a new file

### ISSUE THREAD

**Issue by cedricmessiant** [titoBouzout/SideBarEnhancements#267]
Since the last update of this SidebarEnhancements (I think ?), my Sublime text 3 crashes most of the time when I try to create a new file.

I don't know how to give you more information since the console is closed by the "new file" prompt

**Comment by titoBouzout** [comment]
Disable all third party packages and keep this one enabled.

**Comment by ktraff** [comment]
This is reproducible for me using build 3103

**Comment by n1k0** [comment]
Same problem here.

> Disable all third party packages and keep this one enabled.

So we should all use ST3 with only your package enabled, right?

**Comment by titoBouzout** [comment]
"we should all" nothing. 
you have other package doing weird things, disable all other and start enabling one by one till you fine the one that make it crash

**Comment by n1k0** [comment]
> "we should all" nothing. 

Sorry, I was pissed off, it's not you. Sorry.

FWIW I've just remved and reinstalled the package and the issue is gone. Go figure. Hope it helps others.

**Comment by titoBouzout** [comment]
np, have a nice day
