### ISSUE TITLE
Use Reveal to open a different file manager in Windows ?

### ISSUE THREAD

**Issue by sambody** [titoBouzout/SideBarEnhancements#268]
I'm using Sublime Text on Windows, and often use Reveal (open folder in file manager).
Now I've switched to an alternative file manager (Xyplorer), instead of the default windows File explorer.
Is it possible to have Reveal open a folder using that alternative file manager, instead of the default one?

**Comment by titoBouzout** [comment]
set a custom app in "open with"

**Comment by sambody** [comment]
It worked, thank you.
For reference, this is the code that I'm using (for XYplorer file manager on windows):
```
			{
				"caption": "XYplorer",
				"id": "side-bar-files-open-with-preview",

				"command": "side_bar_files_open_with",
				"args": {
					"paths": [],
					"application": "C:\\Program Files (x86)\\XYplorer\\XYplorer.exe", // double backslashes
					"extensions":"" // any file with these extensions
				}
			},
```

**Comment by dreamfliper** [comment]
It's still good can change default file manager for `Reveal` command, because `open with ...` won't appear when pressing ctrl+alt+p
