### ISSUE TITLE
"Open With" configured with pantheon-terminal on ElementaryOS won't work properly

### ISSUE THREAD

**Issue by ryukinix** [titoBouzout/SideBarEnhancements#271]
## Some printscreens:

# The configuration for the terminal who I have chosen
![captura de tela de 2015-07-26 19 53 40](https://cloud.githubusercontent.com/assets/7642878/8896371/13494744-33d0-11e5-89cf-1964ac8bd8ab.png)

# But it was open a directory — not the C program compiled whose should open
![captura de tela de 2015-07-26 19 53 51](https://cloud.githubusercontent.com/assets/7642878/8896372/138af400-33d0-11e5-9073-a58acc90be8a.png)

**Comment by titoBouzout** [comment]
I dont have enough information. you should be able to do this
