### ISSUE TITLE
When trying to delete a non-existent file, a misleading alert is shown

### ISSUE THREAD

**Issue by marcbachmann** [titoBouzout/SideBarEnhancements#273]
How to reproduce:
- Open file
- CMD+Shift+P -> File: Delete -> Delete selected item
- Don't navigate to a different file and try to delete it again.
- The message **There is no trash bin, permanently delete?** gets shown.

<img width="439" alt="screen shot 2015-07-30 at 2 37 00 pm" src="https://cloud.githubusercontent.com/assets/431376/9038687/8b7004a2-39f6-11e5-8625-326e4342a71c.png">

I'm on Yosemite 10.10.4, using Sublime Build 3083

**Comment by titoBouzout** [comment]
hi! the package does not check for file existence, I would like to keep it that way, since relying on checking if a file exists or not is a good choice in my opinion.
