### ISSUE TITLE
On Windows, please use Windows path format for copy

### ISSUE THREAD

**Issue by ardrigh** [titoBouzout/SideBarEnhancements#274]
If I select any of the current "Copy" options for the path, they all use the unix path / format.
"Copy Path"  
Copy as Text > Relative Path
Copy as Text > Absolute Path
e.g. C:/packages/trunk/filename

Copy as Text > Project folders, uses the correct Windows path format
The right-click menu within a file option "Copy File Path" also uses the correct Windows path format
e.g. C:\packages\trunk\filename

Edit: I notice this "disabled_menuitem_copy_dir_path": true, in the settings file. 
Enabling this option allows path copy of file in Windows format similar to the right click menu. 

It would be nice if there was a Windows format relative or project path version of the "copy_dir_path" option.

It definitely speeds up ability to use these "copy path" options if I don't have to stop to change every / to \ to locate files.

**Comment by titoBouzout** [comment]
why you need paths in Windows way? because all these functions are mean for
Web, but if you can justify... maybe.. m

On Wed, 5 Aug 2015 20:43 Dagan McGregor <notifications@github.com> wrote:

> If I select any of the current "Copy" options for the path, they all use
> the unix path / format.
> "Copy Path"
>
> Copy as Text > Relative Path
> Copy as Text > Absolute Path
> e.g. C:/packages/trunk/filename
>
> Copy as Text > Project folders, uses the correct Windows path format
> The right-click menu within a file option "Copy File Path" also uses the
> correct Windows path format
> e.g. C:\packages\trunk\filename
>
> So this leads me to believe it might be the sidebar package that is not
> converting the path correctly, and not ST3 itself.
>
> It definitely speeds up ability to use these "copy path" options if I
> don't have to stop to change every / to \ to locate files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarEnhancements/issues/274>.
>
-- 

__
Tito

**Comment by ardrigh** [comment]
I have to maintain a various number of windows batch files, bash shell scripts, puppet files and python files. A number of these run Windows EXE files that require Windows file paths. A lot run on Linux servers quite happily also.

Some languages handle file paths where this isn't a problem, but people like me unfortunately still have to work with Windows.

It would make development easier if there was one extra option to provide Windows relative paths for times where Windows path is required.

The option could be disabled by default like the "copy_dir_path" if that is preferred.

**Comment by titoBouzout** [comment]
hi I added option for copying relative to project folder from right click once you set to false
+   "disabled_menuitem_copy_path_windows": true,

currently copy relative to the project folder, like this \Somepath\folder\bla%20bla.txt please let me know if needs some tweaks as Im not sure thats what you want.

**Comment by ardrigh** [comment]
Thank you for adding this :)

**Comment by titoBouzout** [comment]
You are welcome =)

On Thu, 22 Oct 2015 00:28 Dagan McGregor <notifications@github.com> wrote:

> Thank you for adding this :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarEnhancements/issues/274#issuecomment-150096601>
> .
>
-- 

__
Tito
