### ISSUE TITLE
How to close right bar ?

### ISSUE THREAD

**Issue by vu-tuan-mulodo** [titoBouzout/SideBarEnhancements#277]
Dear,
I use the feature "edit to right" and it created a new bar in the right of my exist bar (two bar for editing code). However, I don't know how to close it even I have read your guide on git-hub, or may I lack some guide? Please help me to close it. Does it have a shortcut to close the bar?

**Comment by vu-tuan-mulodo** [comment]
Sorry, I determined it is a feature gird of sublime text. Just go to View -> Layout -> Single to return a single bar for editing code. Please ignore this issue.

**Comment by titoBouzout** [comment]
you can also set in Preferences -> Package Settings -> Sidebar - User Settings

	"auto_close_empty_groups": true

which will close the group to the right, as soon as you close the tab.

**Comment by asimpletimeout** [comment]
Thank you for your question and Thank you for your answer...
