### ISSUE TITLE
Option to disable "There is no trash bin..." warning?

### ISSUE THREAD

**Issue by donmccurdy** [titoBouzout/SideBarEnhancements#278]
I work from NFS drives frequently, and the warning "There is no trash bin, permanently delete?" gets to be pretty repetitive eventually. Is there an option to disable this (I couldn't find one in the settings) or would you accept a PR to add this? Thanks!

**Comment by titoBouzout** [comment]
what about 
	"disable_send_to_trash": true,

Packages -> Preferences -> Sidebar -> Settings - User

**Comment by titoBouzout** [comment]
I see will ask anyways, I would accept a pull request yes

**Comment by titoBouzout** [comment]
here is the relevant portion https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L1301-L1309
