### ISSUE TITLE
open with menu: Open browsers in localhost

### ISSUE THREAD

**Issue by leem32** [titoBouzout/SideBarEnhancements#281]
Hi, Adam,
I'm having a problem opening different browsers in localhost through the "open with" menu.

When i hit F12 it works fine and opens in localhost with firefox which is my default, but if i try to load a browser through the "open with" menu it just opens "file:///" even if i try to load Firefox through this menu.

windows 7 OS

sublimeenhancements.json
```json
{
    "C:/xampp/htdocs/":{
        "url_testing":"http://localhost/"
    }
}
```
sidebar.sublime-menu
```json
[
	{"id": "side-bar-files-open-with",
		"children":
		[
			//application n

			{
				"caption": "Firefox",
				"id": "side-bar-files-open-with-firefox",

				"command": "side_bar_files_open_with",
				"args": {
									"paths": [],
									"application": "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe",
									"extensions":".*", //any file with extension
									"args":[]
						},
				"open_automatically" : false // will close the view/tab and launch the application
			},



			{
				"caption": "Chrome",
				"id": "side-bar-files-open-with-chrome",

				"command": "side_bar_files_open_with",
				"args": {
									"paths": [],
									"application": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
									"extensions":".*", //any file with extension
									"args":[]
						},
				"open_automatically" : false // will close the view/tab and launch the application
			},

					{
				"caption": "Interner Explorer",
				"id": "side-bar-files-open-with-iexplore",

				"command": "side_bar_files_open_with",
				"args": {
									"paths": [],
									"application": "C:\\Program Files\\Internet Explorer\\iexplore.exe",
									"extensions":".*", //any file with extension
									"args":[]
						},
				"open_automatically" : false // will close the view/tab and launch the application
			},

						{
				"caption": "Opera",
				"id": "side-bar-files-open-with-opera",

				"command": "side_bar_files_open_with",
				"args": {
									"paths": [],
									"application": "C:\\Program Files (x86)\\Opera\\launcher.exe",
									"extensions":".*", //any file with extension
									"args":[]
						},
				"open_automatically" : false // will close the view/tab and launch the application
			},

			{"caption":"-"}
		]
	}
]
```
Thanks :)

**Comment by titoBouzout** [comment]
you can set F12 or any other key to load other browser with the "browser" argument.

  { "keys": ["f12"],
            "command": "side_bar_open_in_browser" ,
            "args":{"paths":[], "type":"testing", "browser":"firefox"} //one of this list: firefox, aurora, chrome, canary, chromium, opera, safari
        },

https://github.com/titoBouzout/SideBarEnhancements#f12-key-conflict

**Comment by leem32** [comment]
Hi Tito,
Yeah i already have that setup, but the problem is when I'm browser testing i test on 5 different browsers, but using the 'browser' argument i can only set 2.Oh well not to worry if it's not possible, it's still quicker for me to use the 'open with' menu for all the different browsers than it is to open the browsers manually and type in the url.It just means i have to change file:/// to localhost thats all , but it would have been nice for this to be automatic.
all the bestLee :) 


     On Wednesday, 14 October 2015, 14:01, Tito <notifications@github.com> wrote:
   

 you can set F12 or any other key to load other browser with the "browser" argument.{ "keys": ["f12"],
 "command": "side_bar_open_in_browser" ,
 "args":{"paths":[], "type":"testing", "browser":"firefox"} //one of this list: firefox, aurora, chrome, canary, chromium, opera, safari
 },https://github.com/titoBouzout/SideBarEnhancements#f12-key-conflict—

**Comment by titoBouzout** [comment]
okei, I change the menuitem "open in browser" to be a menu now like this http://i.imgur.com/VGTiRo3.png

Additionally I added IE as a browser, corrected opera and added a menuitem to open all at the same time. You can control via preferences which browsers open

     "open_all_browsers": ["firefox", "chrome", "opera", "safari", "ie"]


If you need to further tweak please let me know.

**Comment by leem32** [comment]
Thank youTito, I've just tested it and it's working perfectly.
This will prove to be a real time saver when doing a load of testing/debugging.
If anyone can't get it to work don't forget to add the new 'open in browser' settings to your sidebar.sublime-menu you can find them here.https://github.com/titoBouzout/SideBarEnhancements/blob/5766930ae0e91807b5ed63bccd8f2831eed7083f/Side%20Bar.sublime-menu
Thanks again :)
 


     On Wednesday, 14 October 2015, 15:55, Tito <notifications@github.com> wrote:
   

 okei, I change the menuitem "open in browser" to be a menu now like this http://i.imgur.com/VGTiRo3.pngAdditionally I added IE as a browser, corrected opera and added a menuitem to open all at the same time. You can control via preferences which browsers open "open_all_browsers": ["firefox", "chrome", "opera", "safari", "ie"]
If you need to further tweak please let me know.—

**Comment by titoBouzout** [comment]
cool, but please don't touch these file, just update the package via
package control. if you update files manually you will mess with the
package and things will not work as well expected, if you have problems to
update it just remove it, remove everything and try installing it via
package control

On Wed, 14 Oct 2015 13:39 leem32 <notifications@github.com> wrote:

> Thank youTito, I've just tested it and it's working perfectly.
> This will prove to be a real time saver when doing a load of
> testing/debugging.
> If anyone can't get it to work don't forget to add the new 'open in
> browser' settings to your sidebar.sublime-menu you can find them here.
> https://github.com/titoBouzout/SideBarEnhancements/blob/5766930ae0e91807b5ed63bccd8f2831eed7083f/Side%20Bar.sublime-menu
> Thanks again :)
>
>
>
> On Wednesday, 14 October 2015, 15:55, Tito <notifications@github.com>
> wrote:
>
>
> okei, I change the menuitem "open in browser" to be a menu now like this
> http://i.imgur.com/VGTiRo3.pngAdditionally I added IE as a browser,
> corrected opera and added a menuitem to open all at the same time. You can
> control via preferences which browsers open "open_all_browsers":
> ["firefox", "chrome", "opera", "safari", "ie"]
> If you need to further tweak please let me know.—
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarEnhancements/issues/281#issuecomment-148110528>
> .
>
-- 

__
Tito
