### ISSUE TITLE
Open With menu not work when trying to open local html files with Chrome on Mac

### ISSUE THREAD

**Issue by daleqq** [titoBouzout/SideBarEnhancements#282]
Due to the Chrome security restriction, to open Chrome with local file must specified the option **--allow-file-access-from-files**. 
I have set the configuration in *Side Bar.sublime-menu* as below:
```
"args": {
					"paths": [],
					"application": "Google Chrome.app",
					"extensions":".*", //any file with extension
					"args": ["--args", "--allow-file-access-from-files"]			
				},
```
But it does not work. 

I found the **open** command usage is like `open [-a application] file [--args arg1 ...]`. 
The code to open with the application in Sidebar is: `subprocess.Popen(['open', '-a', application] + args + [item.name()] ...`.

**I guess whether the args order is the problem or not?**

**Comment by titoBouzout** [comment]
you sure does not work? is --args required?

**Comment by titoBouzout** [comment]
you can set F12 or any other key to load other browser with the "browser" argument.

https://github.com/titoBouzout/SideBarEnhancements#f12-key-conflict
