### ISSUE TITLE
Remove Folder from Project - ability to disable

### ISSUE THREAD

**Issue by puittenbroek** [titoBouzout/SideBarEnhancements#283]
At the moment, when you have a project. The first option in the side bar menu is the mentioned "Remove Folder from Project" command.
This is quite unhandy, I've already intended to add a file and by accident removed my main folder.

Would be nice to be able to disable or move this option.
Like .. being the last option ever :)

**Comment by titoBouzout** [comment]
can you take a screenshot of your menu

On Thu, 8 Oct 2015 12:47 Peter Uittenbroek <notifications@github.com> wrote:

> At the moment, when you have a project. The first option in the side bar
> menu is the mentioned "Remove Folder from Project" command.
> This is quite unhandy, I've already intended to add a file and by accident
> removed my main folder.
>
> Would be nice to be able to disable or move this option.
> Like .. being the last option ever :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarEnhancements/issues/283>.
>
-- 

__
Tito

**Comment by puittenbroek** [comment]
Sure, see attachment
![sublime-menu](https://cloud.githubusercontent.com/assets/1254185/10370125/e2f65b48-6ddd-11e5-8a84-fa77acd52240.png)

**Comment by titoBouzout** [comment]
In packages - browse packages
I have folder Default
with file "Side Bar Mount Point.sublime-menu" and context completely empty

**Comment by puittenbroek** [comment]
Hi @titoBouzout, sorry I don't really understand your comment :(

**Comment by titoBouzout** [comment]
I mean you can get ride of that menuitem, by going to:

1. Main menu-bar - Preferences - Browse Packages
2. There create an empty file ./Packages/Default/Side Bar Mount Point.sublime-menu

The menuitem should disappear. Note that you are already in "Packages" folder, you should just create "Default" (if is not there already)
