### ISSUE TITLE
allow to reorder the context menu elements

### ISSUE THREAD

**Issue by hatarist** [titoBouzout/SideBarEnhancements#288]
Use case: I rarely use "New file" and "New folder" and often use "Rename", "Duplicate" and "Delete". It would be great to have the latter menu items higher. Also, this way we could get rid of the enormous amount of parameters like `disabled_menuitem_edit_to_right` or `disabled_menuitem_copy_path_windows` - we'd just add or remove these elements from the ordered list. I can solve that with customizing a `Side Bar.sublime-menu` file, but wouldn't it rewrite after package update via Package Control?

It seems very convenient, at least for me :)

Also, a minor bug: `disabled_menuitem_open_in_browser` seems to hide the available browsers in the "Open In Browser" menu, but keeps the actual "Open In Browser" menu item.

**Comment by titoBouzout** [comment]
> Also, a minor bug: disabled_menuitem_open_in_browser seems to hide the available browsers in the "Open In Browser" menu, but keeps the actual "Open In Browser" menu item.

okei added for https://github.com/SublimeTextIssues/Core/issues/1095
