### ISSUE TITLE
Donate link invalid

### ISSUE THREAD

**Issue by guyspronck** [titoBouzout/SideBarEnhancements#293]
I would like to give a donation, but the menu option for donate redirect to an invalid donate URL.

**Comment by titoBouzout** [comment]
Looks like works here, what you see?

**Comment by guyspronck** [comment]
This is the exact url that opens when I click the button:
https://www.paypal.com/cgi-bin/webscr?cmd=_flow&SESSION=bLlXri8K69c9TdokTdYD6heEURRnVmsbv77cB7cem1EFhiqPgClRD6zF0ai&dispatch=5885d80a13c0db1f8e263663d3faee8d64ad11bbf4d2a5a1a0d303a50933f9b2

Here is an image of the page I see:
![Issue](http://i.imgur.com/ndUsFX0.png)

Seems like there is an issue with the email address.

**Comment by titoBouzout** [comment]
Hi thank you for the report :) I think that maybe is now fixed, I dont know what happened ^^
