### ISSUE TITLE
Feature Request: Folders & Files Sorting

### ISSUE THREAD

**Issue by r0lodex** [titoBouzout/SideBarEnhancements#294]
Thanks for the great plugin. It'd be awesome if the plugin has the option of sorting files & folders, other than the default alphabetical order. Probably by file type? Cheers!

**Comment by titoBouzout** [comment]
Meanwhile =) https://github.com/SublimeTextIssues/Core/issues/328

**Comment by r0lodex** [comment]
Thanks!
