### ISSUE TITLE
Disable open file with right click

### ISSUE THREAD

**Issue by joelcuevas** [titoBouzout/SideBarEnhancements#295]
Is there any way to prevent opening a file with right click?

This happens to me a lot:

1) Right click on side bar and delete a file
2) The file opens in preview mode
3) SideBarEnhancements prompts for confirmation
4) Confirm and move along
5) The file is still open in preview mode
6) Do stuff and do a "save all"
7) The deleted file is recreated in its original location :(

Is there a setting that I could change? I haven't found nothing.

**Comment by titoBouzout** [comment]
Main menu - Pacakges - Preferences User 
then add this somewhere 
	`"preview_on_click": false,`

In theory preview on click should only work for the left button, but well, we have this issue for tracking https://github.com/SublimeTextIssues/Core/issues/2

**Comment by joelcuevas** [comment]
Oh! I've been using SideBarEnhancements for so long now that I didn't notice that this could be, in fact, a Sublime issue. Thanks for the help! :stuck_out_tongue_winking_eye:
