### ISSUE TITLE
Adding "folder_exclude_patterns" will hide folder even when manually included

### ISSUE THREAD

**Issue by Pictor13** [titoBouzout/SideBarEnhancements#297]
I just edited the *"folder_exclude_patterns"* Sublime setting to exclude my /vendor/ folder, cause I don't want the Goto-Anything index also stuff in there (I keep more the whitelist aprroach). So if I want a folder from /vendor/ I will manually put it in the sidebar.

Unfortunately, setting a filter for that setting also influences *SideBarEnhancements* and will make it filter away all the directories that are under the excluded folder that I included manually. 
Strangely the files instead are still shown.
So if I manually add to the sidebar a folder that was excluded then I will just get the content of the first directory, but I will not get the subfolders of the same directory.

Maybe this is a by-design behaviour but in my case is limiting the functionality of the sidebar.

Is it possible to not consider that setting?
Or is this a behaviour inherited by Sublime?

**Comment by titoBouzout** [comment]
This package does not provide any filtering. If you wish to exclude a folder from the Gogo anything I think the best bet is to right click the folder - Project - and here select one of the "exclude from index" options which will add the selected item to the binary_file_patterns
