### ISSUE TITLE
Permission error when installing 

### ISSUE THREAD

**Issue by donomron** [titoBouzout/SideBarEnhancements#299]
When trying to install using package control, I get this error in the console:
`PermissionError: [WinError 5] Access is denied : c:\\users\\[my_user_name]\\appdata\\local\\temp\\tmph68_i2\\working`
any suggestions?

**Comment by titoBouzout** [comment]
Hi @donomron idk! Some suggestions..
1. maybe running out of space? try cleaning the temp folder by right clicking the harddrive.
2.permissions..? mmh.. try running ST as administrator, right click the icon, chose "run as admin"
3. idk to be honest. be sure the folder c:\\users\\[my_user_name]\\appdata\\local\\temp\\ exists
