### ISSUE TITLE
Rename on slow double click

### ISSUE THREAD

**Issue by felipesotero** [titoBouzout/SideBarEnhancements#300]
I'd be good to have the windows and unix default click-rename feature replicated here.

Is it doable given the current sublime API?

**Comment by titoBouzout** [comment]
Not doable......

**Comment by titoBouzout** [comment]
I suggest to fill a feature request in https://github.com/SublimeTextIssues/Core/issues

**Comment by felipesotero** [comment]
@titoBouzout Thanks!
