### ISSUE TITLE
'New File' from sidebar not creating new file

### ISSUE THREAD

**Issue by jzgdev** [titoBouzout/SideBarEnhancements#301]
When trying to create a new file from the sidebar, for example right clicking a specific folder within a project to create a new file within said project, nothing happens. 

I'm on OSX and using ST3 build 3103

May very well be an issue with some other package I have installed but wanted to bring the bug to your attention.

**Comment by titoBouzout** [comment]
Did you solved the issue? If you can tell what was the problem the better
