### ISSUE TITLE
Package Control Can't Locate

### ISSUE THREAD

**Issue by inspiredmac** [titoBouzout/SideBarEnhancements#304]
In ST3, Package Control can't locate SideBarEnhancements to Install.

**Comment by jcesarmobile** [comment]
+1

**Comment by titoBouzout** [comment]
it works, must be temporal issue

**Comment by jcesarmobile** [comment]
I still don't see it... maybe you have it cached and works for you

**Comment by titoBouzout** [comment]
I'm gonna check again but I don't believe is cached takes an age to load
the list of packages on package control, you may have it disabled

On Sun, Mar 6, 2016, 6:44 AM jcesarmobile <notifications@github.com> wrote:

> I still don't see it... maybe you have it cached and works for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarEnhancements/issues/304#issuecomment-192851991>
> .
>
-- 

__
Tito

**Comment by jcesarmobile** [comment]
What might I have disabled?

**Comment by titoBouzout** [comment]
Or you have the package disable on your settings. OR must be a problem with that hosting Package Control uses. I checked again I can install it just fine

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/SideBarEnhancements#installation

**Comment by jcesarmobile** [comment]
I installed it successfully on another computer, so it might be my problem.
