### ISSUE TITLE
Can't disable items in menu

### ISSUE THREAD

**Issue by max-mykhailenko** [titoBouzout/SideBarEnhancements#305]
Can you add ability to disable all elements in sidebar menu. I need only `clone` and `copy path` and can't configure it.

Current config
```json
{
  "disabled_menuitem_edit": true,
  "disabled_menuitem_edit_to_right": true,
  "disabled_menuitem_open_run": true,
  "disabled_menuitem_open_in_browser": true,
  "disabled_menuitem_open_in_new_window": true,
  "disabled_menuitem_find_in_project": true,
  "disabled_menuitem_copy_name": true,
  "disabled_menuitem_copy_path": false,
  "disabled_menuitem_copy_path_windows": true,
  "disabled_menuitem_copy_dir_path": true,
  "disabled_menuitem_paste_in_parent": true,
  "disabled_menuitem_empty": true,
  "disable_send_to_trash": true,
  "open_all_browsers": false
}
```

I disable almost anything but menu is still big

![image](https://cloud.githubusercontent.com/assets/1213198/13728517/5735d54e-e924-11e5-8d21-2202889cf5b7.png)

* What difference between `reveal` and `open with finder`. How I can delete one of them?
* `Open in browsers` still in items
* `Open with`, `Find and Replace`, `Find files Named`, `File Advanced`, `Cut`, `Copy`, `Copy as Text`, `Move`, `Refresh`, `Project` want to remove
* `Donate` — if I'll donate how I can hide it?

*

**Comment by titoBouzout** [comment]
Hi, is not possible to disable "menus" due to a ST limitation.
I didnt add option to disble all menuitems, but I would accept a pull request. 
I dont want to disable donate menuitem.
