### ISSUE TITLE
Add option to Search In Directory

### ISSUE THREAD

**Issue by ragulka** [titoBouzout/SideBarEnhancements#307]
I always find it a bit frustrating that when I right-click on a folder in sidebar, there's no option to "Find in Folder", there's only "Find in Parent Folder...". It does make sense for files, but for folders, I think the better option is to allow searching in the folder that I right-clicked on.

Atom (text editor) has nailed this - there's only 1 option: "Search in Directory". The directory depends on what's being right-clicked. If it's a directory, then you would search in that directory. If it's a file, then you would search the directory where the file resides in.

**Comment by titoBouzout** [comment]
Is called "find and replace"
