### ISSUE TITLE
FAQ question "show preview in a right click to a file"

### ISSUE THREAD

**Issue by alexkudrow** [titoBouzout/SideBarEnhancements#308]
```
Q: Can the package stop "show preview in a right click to a file".
-   No, ​I'm sorry, can't figure out how to prevent it.
```

Setting `"preview_on_click": false` at user preferencies can solve this problem. But it also removes the ability to view files on by left click.

This may be helpful.

**Comment by titoBouzout** [comment]
https://github.com/SublimeTextIssues/Core/issues/2
