### ISSUE TITLE
FAQ: How to enable status bar to show modified time and file size?

### ISSUE THREAD

**Issue by daniel020403** [titoBouzout/SideBarEnhancements#309]
You release notes says

"Allow to display "file modified time" and "file size" on statusbar via preferences.".

However, there is no documentation on how we can do this. I've tried googling and it doesn't help.
Can you please provide steps as to how we can enable this.

Thanks,
Daniel Garcia

**Comment by TriMoon** [comment]
You need to copy and change some settings from the default settings to the user settings of SBE.
<code>Preferences &rarr; Package Settings &rarr; Side Bar &rArr; Settings - User</code>
```json
{
	"statusbar_modified_time": true,
	"statusbar_modified_time_format": "%A %b %d %H:%M:%S %Y",
	"statusbar_modified_time_locale": "",

	"statusbar_file_size": true,
}
```
You are free to adjust the ``time_format`` and ``time_locale`` :wink:

**Comment by daniel020403** [comment]
Thanks @TriMoon! It's working great. :)
