### ISSUE TITLE
canceling a folder refresh operation freezes sublime_text

### ISSUE THREAD

**Issue by kurazsi** [titoBouzout/SideBarEnhancements#312]
I am running ubuntu 15.10 using i3 as a launcher.
I have a project with a lot of folders.. and subfolders
If i use the mouse to rightclick and delete a folder that causes a slide up of the folder's displayed
(for example if the folder was opened and it occupied let's say 5 lines, and after deletion the entire displayed folder list needs to move up 5 lines) then sublime hangs, and i need to kill it and relaunch it.
The changes (deletion) has been completed. I presume there is a bug with handling the sudden change in the folder structure and where the selected item was, rightclick-ing selects the folder that i want to delete...

How can i debug this ?

**Comment by kurazsi** [comment]
this issue can be reproduced each time, also with the Sublime Dev Build 3111
It happens if a large folder structure is used.
It happens each time there is a significant change of the folder sidebar items. And only if this plugin is installed.

Can someone help me investigate it ?

**Comment by kurazsi** [comment]
SOLUTION: 
change this:
`	def refresh(self):
		try:
			   sublime.set_timeout(lambda:sublime.active_window().run_command('refresh_folder_list'), 200);
			    sublime.set_timeout(lambda:sublime.active_window().run_command('refresh_folder_list'), 1300);
		except:
			pass
`
to this:
`	def refresh(self):
		try:
			sublime.active_window().run_command('refresh_folder_list')
		except:
			pass
`

**Comment by sandy1890** [comment]
@kurazsi 

same problem for me
can you point out where to change the code? thanks

**Comment by axez85** [comment]
@kurazsi 
I experienced same problem.

**Comment by titoBouzout** [comment]
see 
https://github.com/titoBouzout/SideBarEnhancements/issues/323
https://github.com/titoBouzout/SideBarEnhancements/issues/312

**Comment by lavaldi** [comment]
@sandy1890 the file to change is `SideBarAPI.py` in `SideBarEnhancements.sublime-package`
