### ISSUE TITLE
Work on files in Groups?

### ISSUE THREAD

**Issue by Gabriel-p** [titoBouzout/SideBarEnhancements#313]
For what I can see this package works for files inside *Folders*, but not for single files in groups.

Is this by design or am I missing something?

**Comment by titoBouzout** [comment]
this question is answered into the faq, basically that menu is not
extensible so well

On Tue, May 10, 2016, 14:30 Gabriel <notifications@github.com> wrote:

> For what I can see this package works for files inside *Folders*, but not
> for single files in groups.
>
> Is this by design or am I missing something?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarEnhancements/issues/313>
>
-- 

__
Tito

**Comment by Gabriel-p** [comment]
Thanks, I was just pointed to the [TabsExtra](https://packagecontrol.io/packages/TabsExtra) which is able to delete a file right-clicking on its tab.
Cheers.
