### ISSUE TITLE
Examples in F12 with absolute/relative paths

### ISSUE THREAD

**Issue by TriMoon** [titoBouzout/SideBarEnhancements#314]
You should add or note that you can use local files without a local server by using the ``file://`` URI.
Example of my settings on Win10 _not using any server atm_
```json
{
	"public/":{
		"url_testing":"http://localhost/",
		"url_production":"http://domain.tld/"
	},
	"experimental/":{
		"url_testing":"http://experimental/",
		"url_production":"http://domain.tld/"
	},
	"HTML/":{
		"url_testing":"file://\\%MyDocuments%\\Sublime Text\\HTML\\",
		"url_production":"http://domain.tld/"
	},
	"":{
		"url_testing":"file://\\%USERPROFILE%\\Documents\\Sublime Text\\",
		"url_production":"http://the_url_for_the_project_root/"
	}
}
```
- [x] Note in the totally optional <b>"HTML/"</b> example, i used a custom environment variable ``%MyDocuments%`` set for my user account.
  * - [x] This was set as: ``MyDocuments = %USERPROFILE%\Documents``

**Comment by TriMoon** [comment]
not sure what happened but right now the environment variables don't get expanded anymore :confused: 
It worked while i wrote the above..

**Comment by titoBouzout** [comment]
when you use project-dir/.sublime/SideBarEnhancements.json paths should be relative, that is the idea of "project-dir/.sublime/SideBarEnhancements.json", if not use the global config file.
