### ISSUE TITLE
build 3133, SideBarEnhancements not working anything

### ISSUE THREAD

**Issue by Shynoo** [titoBouzout/SideBarEnhancements#315]
I couldn't find it in package settings and any other place.
Of course it is enabled but really seems likely disable.
As right click the file in sidebar it is the same with when I have n't install it. 

Under sublime text 3, build 3133

My settings:
{
	"color_scheme": "Packages/Material Theme/schemes/OLD/Material-Theme-Darker.tmTheme",
	"create_window_at_startup": false,
	"font_size": 13,
	"highlight_line": false,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
	],
	"open_files_in_new_window": false,
	"preview_on_click": false,
	"show_encoding": true,
	"word_wrap": true
}

**Comment by titoBouzout** [comment]
I guess you mean 3113, Im using it with exact that version and it works.  https://github.com/titoBouzout/SideBarEnhancements#installation
