### ISSUE TITLE
how to alter right click menu?

### ISSUE THREAD

**Issue by eromoe** [titoBouzout/SideBarEnhancements#318]
I install a FileHeader package, it add a right click menu `FileHeader`, I want to remove that .What should I do?

**Comment by asimpletimeout** [comment]
哈哈哈...我也手贱点了下..现在在到处找方法移除 右边新开的编辑窗口..

**Comment by titoBouzout** [comment]
ask the package developer of FileHeader to remove the menu

**Comment by eromoe** [comment]
@titoBouzout
But `SideBarEnhancements` does add some extra context menu, it would be much better if you provide a way to manage that
