### ISSUE TITLE
Sublime Hangs on file rename/create/paste/remove 

### ISSUE THREAD

**Issue by nikopolidi** [titoBouzout/SideBarEnhancements#323]
Hello I was having issues with SideBarEnhancements package on ST2. And still having the same issues on ST3.

So when I remove or rename or even create new file Sublime hangs and crashes.
I've just figured out that after removing **SideBarEnhancements** package it works just fine.
So I have to restart sublime each time I make a changes to file tree rename/remove/create file
Here is my details:

Description:	Ubuntu 14.04.4 LTS
Sublime Text Build 3114
SideBarEnhancements: v2016.03.18.06.57.40

![image](https://cloud.githubusercontent.com/assets/4537776/16592831/3668dd72-42eb-11e6-8a51-a1be113e2aa4.png)

**Comment by cody1991** [comment]
I also have this problem when i new a file or folder, or rename etc, the sublime text3 crashes....

**Comment by titoBouzout** [comment]
see 
https://github.com/titoBouzout/SideBarEnhancements/issues/323
https://github.com/titoBouzout/SideBarEnhancements/issues/312
