### ISSUE TITLE
SideBarEnhancements Breaks Symlinks

### ISSUE THREAD

**Issue by rrapstine** [titoBouzout/SideBarEnhancements#324]
So, this used to be an issue with ST3 in general, but it was fixed in build 3033 I believe. ST3 used to not follow symlinks unless you created a new project and explicitly told it to, which meant you couldn't just use a project's directory if your project relied on symlinks.

I'm not entirely sure what about this plugin is causing this, but two things happened after installing this plugin. First, my folders with symlinks had their icons changed to include a pair of arrows pointing opposite directions. Second, ST3 stopped allowing me access to those folders unless I opened them individually in a new window.

Upon removal of this plugin, ST3 returned to normal functionality.

**Comment by titoBouzout** [comment]
I believe the problem has nothing to do with this package, as this package just do adds menuitems to the context menu.
