### ISSUE TITLE
The package specified, SideBarEnhancements, is not available

### ISSUE THREAD

**Issue by Revod** [titoBouzout/SideBarEnhancements#331]
I get this when Open ST3 (Latest Dev build)

_The package specified, SideBarEnhancements, is not available
Package Control: No updated packages_

Sublime Text 3 Dev 3122
Windows 10 x64 With the latest updates (Clean Installation)

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/SideBarEnhancements/issues/327#issuecomment-247087166

**Comment by SimonEast** [comment]
@titoBouzout that link now leads to a 404. Is there an updated link that explains how to fix this error?
