### ISSUE TITLE
SideBarEnhancements was removed from Package Control

### ISSUE THREAD

**Issue by flaub** [titoBouzout/SideBarEnhancements#332]
What would it take to make this distribution channel be reasonable for you? I'm willing to spend some cycles to help get this work smoothly.

**Comment by titoBouzout** [comment]
Well, I'm not sure If I want to distribute the packages there. Everytime I use a distribution channel is a pain in the ass. Firefox addons, apple store, google play, etc. Every single channel tends to add loads of friction and I don't want to spend time on nonsense. They decided to add versions and tagged releases.

I dont want to use versions, for me a date that you already have in the commit, is enough. Semantic versioning does not add any real value. Just friction for no purpose. I understand versioning on npm that everyone depends of everyone else. 

Package control was working just fine, they added this, I dont want to use it anymore.

**Comment by flaub** [comment]
Would you mind if I created a package that tracked this repo on Package Control? You wouldn't have to worry about it and your considerably large user-base would still have a reasonable way of discovering and using your great plugin for Sublime Text. This seems like a win/win for everyone.

**Comment by titoBouzout** [comment]
OK, with some conditions:
- The package name should be "TrackedSideBarEnhancements" to differentiate that is no longer me the one distributing the package.
- The package is distributed with no modifications.
- You are responsible for anything related to that distribution.

If you agree with that, then looks good to me.

**Comment by flaub** [comment]
Two of your terms are in conflict. It's not possible to be responsible for the distribution if one can't make modifications to it (in order to support it).

I can agree to a good-faith effort to only make modifications necessary to support users of the distribution (and not changes to the plugin itself).

Additionally, support for the plugin itself will be deferred to you, the author of the package.

**Comment by titoBouzout** [comment]
I mean, if you intentionally or unintentionally modify something and things goes wrong. If you distributing this package, you are responsible for that distribution. I can only be responsible of what is on https://github.com/titoBouzout/SideBarEnhancements

**Comment by jfi** [comment]
Since you've removed it, are you able to at least provide installation instructions? I can't see any in the README.

**Comment by titoBouzout** [comment]
We discussing something else.

**Comment by jfi** [comment]
@titoBouzout I would have thought it was relevant. You've removed your plugin from Package Control but aren't actually providing installation instructions, meaning it's not easy to install anymore. I just came to install on a new machine and assumed this was a problem with Package Control because it's no longer available. I'm now going to have to go Google on how to install your package from source because you've removed it and haven't provided installation instructions on the README.

:+1: for @flaub's suggestion. Package Control is the de-facto method of package installation and unless you clearly mark "This package is not included in Package Control, here is how to install it" all you're serving to do is confuse your users.

**Comment by titoBouzout** [comment]
Whatever, we discussing something else.

**Comment by Xyc0** [comment]
You can use a single tag and just move it to HEAD when you think a build is stable enough to pull against.
Tagging sounds like a chore but it is there to make it easier to do frequent commits without fear of breaking a build.
It's kind of like having a trunk and dev branch without the unnecessary overhead of a second branch.

**Comment by titoBouzout** [comment]
@flaub I unlocked this issue and removed the unuseful comments. I'm sorry this package been more noisy than I expected. In case you still consider it the discussion is open with you.
