### ISSUE TITLE
Please add back to PackageControl

### ISSUE THREAD

**Issue by ronelliott** [titoBouzout/SideBarEnhancements#334]
Title says it all, I see where you said that you've stopped using PackageControl to distribute your packages, but you've not said why. I have forked this repo, if you don't add it back to PackageControl, I will.

**Comment by kubawolanin** [comment]
+1

**Comment by TheoBr** [comment]
Tone of this is terrible at best. I, too, am curious why this package is no longer on Package Control, but this issue sounds like a threat.

**Comment by titoBouzout** [comment]
There I added a note to the readme https://github.com/titoBouzout/SideBarEnhancements

Now stop harassing me and leave me alone.
