### ISSUE TITLE
Sobre PackageControl y semver

### ISSUE THREAD

**Issue by CieNTi** [titoBouzout/SideBarEnhancements#340]
Buenas tardes Tito,

Me ha dado mucha lástima y mucha rabia ver que tu paquete no está ya en package control, porque esto significa que muchisima gente dejará de seguir tu magnífico trabajo, entre ellos yo ya que no puedo ir añadiendo canales personales por cada paquete que quiera usar (no trabajo en un único ordenador).

Por todo lo que pusiste en README entiendo tu postura, pero pienso que aun estás a tiempo de darte cuenta y reaccionar. Una fecha como versión no tiene sentido, porque para eso se asociará una fecha con la versión ... es como decir asociar una fecha con la misma fecha .. no tiene sentido.

¿Semver es la mejor solución? Psé, es otra mas, yo la sigo en un par de cosas aunque no siempre ... pero si que no cabe duda que es mas intuitiva que tu idea, ya que es facil ver "retrocompatibilidad . features . bugfix" y ver entre 2 versiones diferentes si solo hubo un bug, algo nuevo o un cambio grande.

Como ejemplo: Sabemos que 1.0.1 y 1.25.40 son compatibles entre si, ya que ese "1" indica que no ha habido cambios en la retrocompatibilidad, lo que si hubo son 25 nuevas features, y de la última, 40 correcciones. Si luego generas solo un tag, o ademas un release ya es decisión tuya

Preguntate: ¿Si ves 2 de tus versiones, sacas alguna información sin leer readme/changelog?

Independientemente, vi que apenas hay "releases" ¿Sólo usas git para ir añadiendo cosas ... sin controlar realmente las versiones, branches, releases y tags? Esto explicaría por te pones en contra de un sistema para nombrar versiones, como es semver, y te mantienes firme usando algo que para el resto de personas no es util, como es una fecha (que ya se extrae del propio registro de commits)

Mas por ti que por el resto, aprende o inventa un sistema de nombrado de versiones. Usar una fecha no es util y te acabará liando.

Muchisimas gracias por tu trabajo, y espero que tomes esta nota como consejo y aprecio antes que como un ataque.

Un placer haber usado tu paquete durante este tiempo, espero que vuelva a package control.

Gracias, CieNTi

**Comment by titoBouzout** [comment]
Saludos CieNTi, el paquete ya está de vuelta. La verdad entiendo lo que dices y lo comparto pero no tengo ni el más mínimo interés. Versión 1, 2, 5, 13...... no dice nada. 

Semver es útil para NPM que no puedes actualizar un paquete "a ciegas" si ves que la versión tiene "breaking changes". 

Deberías de poder instalarlo perfectamente y en cualquier caso me dices. 

Saludos! :)

**Comment by CieNTi** [comment]
Muchas gracias, tanto por re-habilitarlo, como por la respuesta.

Un placer
