### ISSUE TITLE
ST3 default New Folder etc. right click items still present but greyed out

### ISSUE THREAD

**Issue by iamed2** [titoBouzout/SideBarEnhancements#407]
Right-clicking on a file gives me this: 
<img width="193" alt="screenshot 2019-02-07 11 52 59" src="https://user-images.githubusercontent.com/3131001/52432037-11fe8300-2acf-11e9-82be-76d7170b7c14.png">

The New Folder / Rename / etc. items from ST3 remain in the menu but are greyed out. Better to be greyed out than have two available options for the same action, but it would be nice if they were gone altogether. Or if the SideBarEnhancements items were above all the greyed-out items.

**Comment by titoBouzout** [comment]
Post here please https://forum.sublimetext.com/t/dev-build-3187-plugin-is-visible-broke/41462

I dont know if theres any other way to hide default items.

**Comment by titoBouzout** [comment]
you using a dev version right?

**Comment by iamed2** [comment]
Sure thing

Yep, dev 3189

**Comment by titoBouzout** [comment]
Issue logged as https://github.com/SublimeTextIssues/Core/issues/2620

**Comment by titoBouzout** [comment]
this been fixed BUILD 3190
