### ISSUE TITLE
Bug: Create file in selected folder using shortcuts

### ISSUE THREAD

**Issue by ViggoV** [titoBouzout/SideBarEnhancements#411]
When calling the `side_bar_new_file` command via a key binding ("super+shift+n" in my case), while the side bar is focused and a folder is selected, the file is created in the same folder as the last used view. That means you can't create a file in an empty folder, or a folder containing only other folders. I was under the impression that the new file/new folder functionality were analogous with picking the corresponding options from the right-click menu of the currently selected item.

If, as I suspect, this is not possible, I think it makes a good argument for my recently created feature request: #410

**Comment by titoBouzout** [comment]
When you right click an item in the sidebar, you know what path you clicked. When you dont use the right click, we have no way to see what's selected.

May be related to this also https://github.com/SublimeTextIssues/Core/issues/306
