### ISSUE TITLE
Open in browser not pointing to server

### ISSUE THREAD

**Issue by tomgreenfield** [titoBouzout/SideBarEnhancements#414]
### Problem

The open in browser functionality hasn't worked for me since version 5.0.33.

The current behaviour only opens the file locally in the browser.

### Configuration

Located at `D:\working\.sublime\SideBarEnhancements.json`:
```json
{
	"": {
		"url_testing": "http://localhost:8888"
	}
}
```
Expected URL: `http://localhost:8888/web/alpha/index.html`
Actual URL: `file:///D:/working/web/alpha/index.html`

### Solution

Reverting this [line](https://github.com/titoBouzout/SideBarEnhancements/compare/5.0.33...HEAD#diff-0d4da8d8bf21ca5c7236c26ee23971e2R362) fixes it for me.

### Versions

Sidebar Enhancements 5.0.38
Sublime Text 3.2.1, Build 3207
Windows 10 Pro

**Comment by titoBouzout** [comment]
I belive this should be working

**Comment by colinrei** [comment]
This is not working again, see my open issue...
https://github.com/titoBouzout/SideBarEnhancements/issues/440

**Comment by colinrei** [comment]
> I believe this should be working

This is not working again, see my open issue...
https://github.com/titoBouzout/SideBarEnhancements/issues/440
