### ISSUE TITLE
Hi, is there any way i can open with other terminal app?

### ISSUE THREAD

**Issue by HendraPrasetya1991** [titoBouzout/SideBarEnhancements#416]

**Comment by Asutu** [comment]
Same question here. I'm working on a MacOS and recently changed to using iTerm2. 

Looked at [#369](https://github.com/titoBouzout/SideBarEnhancements/issues/369) but can't seem to find a way to implement this.

**Comment by 52fisher** [comment]
Not sure what you mean.
U can enter these statements into the terminal (mac/Linux etc.) like `sublime demo.txt` , then u can open this file with sublime.
if u wanna realize functions as  SideBarEnhancements with other apps , just search about it on Plugin Central.
