### ISSUE TITLE
File operations freeze sublime for 20 seconds

### ISSUE THREAD

**Issue by skimania** [titoBouzout/SideBarEnhancements#417]
New file, rename file, delete file, etx all cause the Sublime UI to lock up for 10-30 seconds
I'm running CentOS Linux 7
I was using a 3 year old version of SideBarEnhancements for the last 3 years (never updated via package manager) but this problem started recently. Could be an external change.
Not sure how to debug this issue.

**Comment by titoBouzout** [comment]
is the file or folder remote?

**Comment by titoBouzout** [comment]
try updating it btw

**Comment by skimania** [comment]
Files are local. I tried updating today.

**Comment by titoBouzout** [comment]
try disabling the other third party packages

**Comment by sphuber** [comment]
I am also experiencing the same problem on Ubuntu 18.04 since at least a few months. Don't remember exactly when it started showing up. I also have no idea how to debug this in order to provide more information. Hints are very welcome.
