### ISSUE TITLE
include open pdf by default

### ISSUE THREAD

**Issue by TejasAvinashShetty** [titoBouzout/SideBarEnhancements#418]
Dear maintainers,
Opening a pdf is a common activity.
Hence, I suggest making it a default feature.
[open with pdf.gist](https://gist.github.com/TejasAvinashShetty/926f856e68f8a2d706e90d022c9e126a)

**Comment by titoBouzout** [comment]
I have been opening PDFs with chrome.  Maybe try to configure your system to open the PDF with the app that you want
