### ISSUE TITLE
Open With fails with terminator

### ISSUE THREAD

**Issue by jelek21** [titoBouzout/SideBarEnhancements#419]
Hi,
I tried to configure a new "Open with" item to open with terminator (the terminal I am using all day long), I did use a configuration found in an older issue : [#369](https://github.com/titoBouzout/SideBarEnhancements/issues/369)
It works quite well with gnome-terminal, but I could not make it work with terminator :
```
{
        "caption": "Terminal",
        "command": "side_bar_files_open_with",
        "args": {
        "paths": [],
        "application": "/usr/bin/terminator",
        "extensions":"",
        "args":["--working-directory=$PROJECT"]
    },
    "open_automatically" : false
},
```
It does nothing when I hit the item...
I also tried with xterm and got also nothing...
I tried to look in the console but nothing showed up... Is there any way to get some traces?

**Comment by titoBouzout** [comment]
Hello, there I removed the try and except

**Comment by dylan7581** [comment]
Hello, thanks you, now it working with that :
```
{
    "caption": "Terminator",
    "id": "side-bar-files-open-with-terminator",
    "command": "side_bar_files_open_with",
    "args": {
        "paths": [],
        "application": "terminator", // OSX
        "extensions":"",  //any file with these extensions "psd|png|jpg|jpeg"
        "args":["--working-directory"]
    },
    "open_automatically" : false // will close the view/tab and launch the application
},
```

**Comment by titoBouzout** [comment]
cool ♥
