### ISSUE TITLE
Easy way to customize the menu?

### ISSUE THREAD

**Issue by stevenvachon** [titoBouzout/SideBarEnhancements#421]
There seems to be limited `disable_*` options and editing the installed _Side Bar.sublime-menu_ file will be overwritten by the next update.

Ultimately, I'm only currently interested in the "Duplicate" option.

**Comment by titoBouzout** [comment]
theres some preferences for hidding items, but you cant hide them all I think I do not remember
anyway if you gonna use just 1 function of this, then make a new plugin that does that, is very simple

**Comment by tablatronix** [comment]
Ditto, there are too many things here I never even use, I want the old st2 sidebar enhancements only, find in parent, find in project etc.
