### ISSUE TITLE
Create a build system for html and bind to open in browser?

### ISSUE THREAD

**Issue by artt** [titoBouzout/SideBarEnhancements#422]
Not really an issue (sorry) but I thought I'd ask anyways. Is there a way I could create a build system so that when I press `Ctrl+B` it opens the file in browser? Thanks!

**Comment by titoBouzout** [comment]
I guess you can create one yes https://www.sublimetext.com/docs/3/build_systems.html

the basic example seems to use python, you may be able to modify it a bit to run your own python file that will do the opening in browser thingy, I dont use build systems, but I guess something around this lines should work:

```
{
    "cmd": ["python", "myopeninbrowser.py", "$file"],
    "selector": "source.html",
    "file_regex": "^\\s*File \"(...*?)\", line ([0-9]*)" // Im not sure about this line
}
```

then on myopeninbrowser.py should have some code similar to this 

```python

import webbrowser
import sys

file = sys.argv[1]
url = 'http://localhost/'+ file.replace('your path', '')
print(url)

new = 2 # open in a new tab, if possible
webbrowser.open(url,new=new)

```

this is just an example and wont work most likely but you get the idea
