### ISSUE TITLE
High CPU used and Memory leak after putting many folders (with a lot files) stick on sidebar

### ISSUE THREAD

**Issue by neikxd** [titoBouzout/SideBarEnhancements#423]
Sublime Text 3.2.2 build 3211.

Every time I open sublime text 3, it took a lot of time with high CPU used and memory was increased without stopping (200MB > 1GB > 2GB >...) --> made Sublime Text with no response. Seem it's trying to scan every files inside folder on sidebar --> make this problem

Took me a lot of time to diagnose this problem. I had to remove each package to figure out what caused my problem. Then when I removed all folder on sidebar --> problem gone.

BR!

**Comment by titoBouzout** [comment]
Hello, I dont remember this package scanning folders, your issue could be related to indexing, thats a sublime text thing.

**Comment by Electrk** [comment]
i've had the same issue - it's sublime's indexing
