### ISSUE TITLE
List of all commands?

### ISSUE THREAD

**Issue by urtvs** [titoBouzout/SideBarEnhancements#424]
Hi

How to get the names and args of all commands of sidebarEnhancements?
I need to find name of toggle side bar enhanced

Thanks a lot!

**Comment by dajnz** [comment]
As a temporary solution, you can use the search for **Command(** in [this file](https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py). Found class names without **Command** word converted to snake_case (like **SideBarCopyTagStyleCommand** -> **side_bar_copy_tag_style**) will give you available commands, but unfortunately without detailed comments.
