### ISSUE TITLE
SublimeText 4 support

### ISSUE THREAD

**Issue by domibarton** [titoBouzout/SideBarEnhancements#426]
Hi

First of all, thanks all the contributors for the amazing work at SideBarEnhancements. I know how much effort it takes to create & maintain open source projects! :)

I recently switched to ST4 and I experience some weird side effects with SideBarEnhancements. Before I go into details, are there any plans to support ST4 or is someone working at it? I'd love to see support for ST4, but I understand it's open source and one cannot simply "demand" for it ;)

In case there's currently nobody working on it, I'd probably have a look at the code myself and see if I can help out. However, I'd be quite happy to get some help as well.

The things I'm currently aware of not working w/ ST4 are:

- The original `New File` entry is back, probably due to code changes at [the NewFileAtCommand class](st3/SideBarDefaultDisable.py#L4)

![image](https://user-images.githubusercontent.com/4124099/110797672-9d800a80-8279-11eb-813f-105fc962bb82.png)

- When I use the `New File` of SBE, it sometimes creates the file in multiple places the same time (the selected directory and the directory of the currently opened / focused file in ST)
- The same appears for `Delete File`, which deletes the *wrong* file (same behaviour as the `New File` problem)
- Sometimes `Duplicate`, `Delete` and other items are just greyed out and I've to click in the sidebar multiple times until it appears enabled again

![image](https://user-images.githubusercontent.com/4124099/110798163-2f881300-827a-11eb-8678-a074fef1b8e6.png)

Is there anybody out there who can probably point me in the right direction in reverse engineering & fixing this issue? :)

Cheers
Domi

**Comment by titoBouzout** [comment]
ST4 doesn't seem to be in public beta yet, I have seen some links and some change logs. Im not sure, I think my licence won't work on it, currently on ST3 says Licence Upgrade Required and I bought it like 3 or 4 times already. To be honest unless they manage to fix the million of bugs and quirks on the APIs I won't be genuinely interested in upgrading, I may upgrade just to support their work not the changes itself.

**Comment by phaistonian** [comment]
Also, [this](https://forum.sublimetext.com/t/on-open-in-new-window/56614).

**Comment by titoBouzout** [comment]
I downloaded ST4 from the discord server and seems to mostly work fine.

> """"open in new window doesnt work""""

yeah that seems to be a problem 

> """"the stock ST4 menuitems are there""""

yeah, to be honest no idea how to disable these stock items, what I have done is to create an empty file named "Side Bar.sublime-menu" on Menu - Browse Packages - Default/Side Bar.sublime-menu

> The same appears for Delete File, which deletes the wrong file (same behaviour as the New File problem)

SBE doesn't provide an item named "delete file" that must be ST4, on SBE is just "Delete". Instead of using the items on top use the ones on bottom

**Comment by dndrsn** [comment]
@titoBouzout 

> yeah, to be honest no idea how to disable these stock items, what I have done is to create an empty file named "Side Bar.sublime-menu" on Menu - Browse Packages - Default/Side Bar.sublime-menu

Thanks for that.  That works perfectly.  Probably worth adding to the readme.

**Comment by silverwind** [comment]
ST4 is out, I'd say it's time to remove the conflicting menu entries.

**Comment by skunkworker** [comment]
It seems like Sublime 4 broke the "Open in New Window" command that used to work on folders and files. Which when broken surprised me how much I rely on that day-to-day.

**Comment by skunkworker** [comment]
Doesn't `New File` in ST4 create a new file without the `File Name:` prompt but with SBE it prompts for the location? It could be renamed to `New File with name` or something similar.

**Comment by christiangenco** [comment]
The top `New File` creates a new file without prompting me for a path (which I think is the ST4 default `New File`). The bottom `New File` is the version from `SideBarEnhancements` that prompts me for a file path before creating the file (which is so much better).

<img width="222" alt="Screen Shot 2021-06-25 at 4 50 49 PM" src="https://user-images.githubusercontent.com/179361/123488410-84eff200-d5d5-11eb-8790-7783b1a74095.png">

I think what I want is for the ST4 default `New File` and `New Folder` to be hidden.

**Comment by heyvito** [comment]
Hey folks, just a heads-up: Most of those issues should be fixed by #433 ✨
@titoBouzout already released a new version. 🙌🏻

**Comment by titoBouzout** [comment]
Thanks!
