### ISSUE TITLE
Issue on create file and create folder

### ISSUE THREAD

**Issue by suhardiyan** [titoBouzout/SideBarEnhancements#434]
After update sublime to 4121, create file and create folder seems not working

when I press Enter, its not creating file/folder, but add new line to input text

how can I fix this ? 

thankyou

**Comment by apisklov** [comment]
+1

**Comment by h-e-a-p** [comment]
+1 
Are there any solutions? I have been unable to create new file or folder by the sidebar in past few days!

**Comment by apisklov** [comment]
+1

**Comment by dportalesr** [comment]
I managed to make it work without a patch or updating Sublime, but not sure how I did that.

First, I reinstalled the package but no luck, apparently. I disabled every other package to detect any conflicts but also that didn't worked. Then I deleted a few files in my Packages/User folder and at some point it started working again. So I suspect some old settings from other package or this one was causing it. If I had more time I would have investigated further. However, it doesn't seem to be directly related to SublimeText or SBE :/

**Comment by eastplum** [comment]
I've tried delete `Packages\Default` above, but not worked.
The way it worked for me is:
**delete** `sublime_text\Data\Packages\User\Preferences.sublime-settings` and **restart** Sublime Text, then it's fine.
Not sure the reason is I tried all methods then did this or not.

**Comment by suhardiyan** [comment]
> > I managed to make it work without a patch or updating Sublime, but not sure how I did that.
> > First, I reinstalled the package and restarted ST but no luck, apparently. I disabled every other package to detect any conflicts but also that didn't worked. Then I deleted a few files in my Packages/User folder and at some point it started working again. So I suspect some old settings from other package or this one was causing it. If I had more time I would have investigated further. The point is, that it doesn't seem to be directly related to SublimeText or SBE :/
> 
> Hey, your reminder I found the problem, caused by the `Default (Windows).sublime-keymap` file in the `Packages\Default` directory. The new version deletes two configurations, so when the solution is to delete the `Default` directory in the `Packages` directory, then restart the **subl** generation New `Default`. ![image](https://user-images.githubusercontent.com/10894778/139615739-9d138b28-1304-4087-af1f-efc5b521d2d1.png)

Hi,

thanks..

It works,

I need delete all file inside Default folder, then restart sublime text
