### ISSUE TITLE
top level "Find in Folder" removed?

### ISSUE THREAD

**Issue by kentliau** [titoBouzout/SideBarEnhancements#435]
I love to use the top level "Find in Folder", instead of the Find & Replace or other more advance Find. May I know the reason why it is removed?

**Comment by titoBouzout** [comment]
Isnt the same? You just press find instead of replace

**Comment by kentliau** [comment]
when you do different search the top level "Find in Folder" will remember the search, but Find & Replace if you search another terms, the previous tab will become blank

**Comment by titoBouzout** [comment]
Thanks, its fixed, it looks like the "Edit" library that I have been using everywhere is broken !
