### ISSUE TITLE
Python 3.8, File: Delete Unable To Find Trash

### ISSUE THREAD

**Issue by michaelmagistro** [titoBouzout/SideBarEnhancements#437]
Commit 5791fbf2d91aea953c3750bd186561ae8b1ca75d has caused the send2trash library to lose track of where the Windows trash is.

When using the command File: Delete, the command will no longer send the file to trash, but rather display the prompt message "There is no trash bin, permanently delete?".

**Comment by titoBouzout** [comment]
@heyvito any idea how to fix this xD

**Comment by heyvito** [comment]
Hmm. I'm not a Windows user, but I can spin up a VM and try to figure out during the weekend. 😄

**Comment by titoBouzout** [comment]
Much appreciated!

**Comment by titoBouzout** [comment]
I reverted that commit
