### ISSUE TITLE
rename file , press enter don't work

### ISSUE THREAD

**Issue by Yliku** [titoBouzout/SideBarEnhancements#438]
sublime 3, 
when rename file, duplicate or create new file, 
all of this ,when press enter to done, it don't work , it turn to new line;

**Comment by orlandodiaz** [comment]
Upgraded to build 4121 and now having this issue as well. rename, duplicate, and maybe others dont work

**Comment by titoBouzout** [comment]
have you updated this package?

**Comment by orlandodiaz** [comment]
I removed and installed the package again yes

**Comment by orlandodiaz** [comment]
I got it working again by reverting sublime to 4107 for now

**Comment by Yliku** [comment]
Thx, I remove sublime 3 and all setting files(C:\Users\...\AppData\Roaming\Sublime Text 3)
and install sublime 4, and then installed this package, and it works!

**Comment by Yliku** [comment]
> Thx, I remove sublime 3 and all setting files(C:\Users...\AppData\Roaming\Sublime Text 3)
> and install sublime 4, and then installed this package, and it works!



> I got it working again by reverting sublime to 4107 for now
