### ISSUE TITLE
Open In Browser not working (JSON decode error in log)

### ISSUE THREAD

**Issue by colinrei** [titoBouzout/SideBarEnhancements#440]
The side_bar_open_in_browser option tied to a keyboard binding shortcut is suddenly not working anymore.

More specifically, the two keybinding shortcuts for "testing" and "production"

I've tried... 

- Uninstalling the package and removing all files manually from the library folder
- Changing the keybinding shortcut
- Removing recent plugins installed (that could be conflicting)

...but no luck.

Has anybody else experienced this issue?

**Comment by colinrei** [comment]
More details from the console log.
<img width="1526" alt="Screen Shot 2021-12-21 at 10 55 05 AM" src="https://user-images.githubusercontent.com/481315/146968707-d63fc3d1-862f-48b5-a0e0-d60f28811c7a.png">

Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "/Users/colin/Library/Application Support/Sublime Text 3/Installed Packages/SideBarEnhancements.sublime-package/SideBar.py", line 2369, in run
  File "/Users/colin/Library/Application Support/Sublime Text 3/Installed Packages/SideBarEnhancements.sublime-package/SideBarAPI.py", line 357, in url
  File "./python3.8/json/__init__.py", line 370, in loads
  File "./python3.8/json/decoder.py", line 337, in decode
  File "./python3.8/json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 120 column 3 (char 4527)
Unable to open /Users/colin/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings

**Comment by colinrei** [comment]
Hoping somebody could assist with this...

For a workaround, I've just been using the default "sublime-view-in-browser" in the project settings, but this only works if you have the project open from the root folder, and not subfolders within the root.

This is possibly one of the most used features for me in the sidebar enhancements plugin and has severely disrupted my workflow. 

Any help or insight would be appreciated of what I can do.

Again, this is when you right click on the sidebar and set up your preview URLs. Neither the keyboard binding shortcut works, or when you right click on the sidebar to "Open In Browser" for sidebar enhancements, it just does nothing, and throws the above error.

<img width="499" alt="Screen Shot 2022-01-06 at 9 50 39 AM" src="https://user-images.githubusercontent.com/481315/148410833-a542fabf-8ff0-406a-aa03-39af88f26faf.png">

<img width="463" alt="Screen Shot 2022-01-06 at 9 51 48 AM" src="https://user-images.githubusercontent.com/481315/148410854-a962c821-cd06-49fe-9cb6-018bea6f9ce6.png">

**Comment by titoBouzout** [comment]
json error means the file is failing to parse, and I suspect is the comma you have on that screenshot  at the cursor position in line 135
