### ISSUE TITLE
Can't create a new File or create folder.

### ISSUE THREAD

**Issue by jingyuexing** [titoBouzout/SideBarEnhancements#445]
when i input file name and folder.then press Enter, will be like this:
![image](https://user-images.githubusercontent.com/19589872/174446868-21cec02d-0084-4969-bf75-28ce43d2047b.png)

**Comment by jingyuexing** [comment]
Sublime Text version is: 4131

**Comment by titoBouzout** [comment]
mmh, doesnt happen to me

**Comment by jingyuexing** [comment]
> mmh, doesnt happen to me

you use it sublime 4131 or >=4130?

**Comment by titoBouzout** [comment]
yes

**Comment by titoBouzout** [comment]
so, what was the problem?

**Comment by jingyuexing** [comment]
> so, what was the problem?

this problem because a key bind conflict, maby with ChineseLocalization extension, i remove this extension,then,this problem is fixed
